version: '3'
services:
  blog-max:
    build:
      context: .
      args:
        nginx_port: 8888
    ports:
      - "8888:8888"
    env_file:
      - blog.env
    volumes:
      - ./files:/django_steps/mysite/common_static/files:Z
