apiVersion: v1
kind: Pod
metadata:
  name: secret-vars-pod
  annotations:
      pod.beta.kubernetes.io/init-containers: '[{"image": "postgres:9.4", "name": "blog-db", "env": [{"valueFrom": {"secretKeyRef": {"name": "secret-vars", "key": "DBUSER"}}, "name": "POSTGRES_USER"}, {"valueFrom": {"secretKeyRef": {"name": "secret-vars", "key": "DBPASS"}}, "name": "POSTGRES_PASSWORD"}, {"valueFrom": {"secretKeyRef": {"name": "secret-vars", "key": "DBNAME"}}, "name": "POSTGRES_DB"}, {"valueFrom": {"secretKeyRef": {"name": "secret-vars", "key": "DBHOST"}}, "name": "DBHOST"}, {"valueFrom": {"secretKeyRef": {"name": "secret-vars", "key": "DBPORT"}}, "name": "DBPORT"}]}]'
spec:
  containers:
    - name: blog
      image: inavas/django_steps:blog
      env:
        - name: DJANGO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: secret-vars
              key: DJANGO_SECRET_KEY
        - name: DJANGO_SUPERUSER
          valueFrom:
            secretKeyRef:
              name: secret-vars
              key: DJANGO_SUPERUSER
        - name: DJANGO_SUPERPASS
          valueFrom:
            secretKeyRef:
              name: secret-vars
              key: DJANGO_SUPERPASS
        - name: DBNAME
          valueFrom:
            secretKeyRef:
              name: secret-vars
              key: DBNAME
        - name: DBUSER
          valueFrom:
            secretKeyRef:
              name: secret-vars
              key: DBUSER
        - name: DBPASS
          valueFrom:
            secretKeyRef:
              name: secret-vars
              key: DBPASS
        - name: DBHOST
          valueFrom:
            secretKeyRef:
              name: secret-vars
              key: DBHOST
        - name: DBPORT
          valueFrom:
            secretKeyRef:
              name: secret-vars
              key: DBPORT
